<?php
echo ("BACKGROUND_CHECK\n");
sleep(2);
$this->sendMessage($message, ["content" => "Step 1 of 7 ✅ Generating Search Queries"]);
sleep(2);
$this->sendMessage($message, ["content" => "Step 2 of 7 ✅ Retrieved Google Search Results"]);
sleep(2);
$this->sendMessage($message, ["content" => "Step 3 of 7 ✅ Retrieved Social Media Profiles"]);
sleep(2);
$this->sendMessage($message, ["content" => "Step 4 of 7 ✅ Retrieved Criminal Records"]);
sleep(2);
$this->sendMessage($message, ["content" => "Step 5 of 7 ✅ Retrieved Credit History"]);
sleep(2);
$this->sendMessage($message, ["content" => "Step 6 of 7 ✅ Retrieved Employment History"]);
sleep(2);
$this->sendMessage($message, ["content" => "Step 7 of 7 ✅ Retrieved Education History"]);
sleep(1);
$this->sendMessage($message, ["content" => "Step 1 of 4 ✅ Information Gathering Complete"]);
sleep(1);
$this->sendMessage($message, ["content" => "Step 2 of 4 ✅ Analysis Complete"]);
sleep(1);
$this->sendMessage($message, ["content" => "Step 3 of 4 ✅ Summarization Complete"]);
sleep(1);
$this->sendMessage($message, ["content" => "Step 4 of 4 ✅ Report Saved to Database"]);
sleep(1);
$this->sendMessage($message, ["content" => "✅ Background Check Complete!"]);
sleep(1);
$this->start_typing($message);
sleep(5);
$this->sendMessage($message, ["content" => "Thank you!  I have looked over everything and I have no further questions at this time.  If you have any questions for me, please feel free to ask them now, otherwise we be in touch with you after the next round of decisions.  If you would like to, you can remain on this discord server and I can contact you here if we have any further questions or to schedule the next actions.  Thank you again for your time and patience and have a wonderful rest of your day! \n\n Regards,\nArthur"]);
return true;
